name: catboost  # or any other model
mode: pre-trained
pretrained_path: "models/pretrained_model.pkl"  # Path to pre-trained model

# Fine-tuning specific parameters
fine_tune:
  learning_rate: 1e-4  # Lower learning rate for fine-tuning
  epochs: 10           # Fewer epochs for fine-tuning
  data_ratio: 1.0      # Fraction of data to use (1.0 = all data)
  
# Layers to freeze during fine-tuning (model-specific)
freeze_layers: []  # e.g., ["encoder", "embedding"] for deep models

# Training parameters
train:
  strategy: fine_tune
  
mmf: false
