max_seed: 5
tasks:
# Absorption
- caco2_wang
- hia_hou
- pgp_broccatelli
- bioavailability_ma
- lipophilicity_astrazeneca
- solubility_aqsoldb
# Distribution
- bbb_martins
- ppbr_az
- vdss_lombardo
# Metabolism
- cyp2d6_veith
- cyp3a4_veith
- cyp2c9_veith
- cyp2c9_substrate_carbonmangels
- cyp2d6_substrate_carbonmangels
- cyp3a4_substrate_carbonmangels
# Excretion
- half_life_obach
- clearance_microsome_az
- clearance_hepatocyte_az
# Toxicity
- ld50_zhu
- herg
- ames
- dili