defaults:
  - model: catboost-per-task  # Default to per-task CatBoost training
  - job: basic

# Device configuration
device: "cpu"

# Data configuration
data:
  path: "data/"
  benchmark: "caco2_wang"  # Default benchmark

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: null     # Optional: "logs/benchmark.log" to write to file
