defaults:
- model: catboost_gnn
- job: all

hydra:
  run:
    dir: output/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: output/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  output_subdir: .hydra