defaults:
- model: catboost-per-task
- job: basic

hydra:
  run:
    dir: output/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: output/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  # job:
  #   chdir: true
  output_subdir: .hydra